required = [
  # Needed for apimachinery generation
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/gengo/args",

   # Needed for docs generation
  "k8s.io/code-generator/cmd/openapi-gen",
  #"github.com/kubernetes-incubator/apiserver-builder/cmd/apiserver-boot",
  #"github.com/kubernetes-incubator/apiserver-builder/cmd/apiregister-gen",
  "github.com/kubernetes-incubator/reference-docs/gen-apidocs",

]

#[prune]
#  go-tests = true
#  non-go = false
#  unused-packages = true
#
#  # Don't prune helper scripts from code-generator
#  [[prune.project]]
#    name = "k8s.io/code-generator"
#    unused-packages = false
#    non-go = false

[[override]]
  name = "k8s.io/gengo"
  revision = "01a732e01d00cb9a81bb0ca050d3e6d2b947927b"
  #0689ccc1d7d65d9dd1bedcc3b0b1ed7df91ba266
  
[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.6"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.6"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.6"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.6"

[[constraint]]
  name = "github.com/coreos/etcd-operator"
  version = "v0.9.4"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "v1.4.0"
