module "network" {
  source                 = "../modules/network"
#  nat_interface_id       = "${module.compute.nat_interface_id}"
#  nat_interface_id-az2   = "${module.compute.nat_interface_id-az2}"
  vpc_cidr               = "${var.vpc_cidr}"
  private_subnets        = "${var.private_subnets}"
  subnetname             = "${var.subnetname}"
  public_subnets         = "${var.public_subnets}"
  subnetname-pub         = "${var.subnetname-pub}"
  public_subnets-az-two  = "${var.public_subnets-az-two}"
  subnetname-pub-az-two  = "${var.subnetname-pub-az-two}"
  private_subnets-az-two = "${var.private_subnets-az-two}"
  subnetname-az-two      = "${var.subnetname-az-two}"
  region                 = "${var.region}"
  az1                    = "${var.region-az1}"
  az2                    = "${var.region-az2}"
  env                    = "${var.env}"
  id                     = "${var.id}"
  eip_creation           = false
  vpc-state              = "primary"
  region-zoneid          = "${var.region-zoneid}"
}

#module "compute" {
#  source                              = "../modules/compute"
#  region                              = "${var.region}"
#  #vpc-state                           = "primary"
#   cloud-http                          = "${module.network.cloudops-http-SG}"
#   public_subnet_id_cloudops          = "${module.network.cloudops}"
#  env                                 = "${var.env}"
#  id                                  = "${var.id}"
#cloudops_instance_               = "${var.cloudops-count}"
#  instance-type-cloudops              = "${var.instance-type-co}"
#  cloudops_instance_id                = "${module.compute.cloudops_instance_id}"
#  cloudops_instance_id_az2            = "${module.compute.cloudops_instance_id_az2}"
#  region                              = "${var.region}"
#  az1                                 = "${var.region-az1}"
#  az2                                 = "${var.region-az2}"
#  region-zoneid                       = "${var.region-zoneid}"
#  region-key                          = "${var.region-key}"
#  region-domain                       = "${var.region-domain}"
#  nat_priv                            = ""
#}
